CREATE TABLE "SCOTT"."COMMENTS" 
   (	"COMMENT_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"BOARD_ID" NUMBER(8,0), 
	"NICKNAME" VARCHAR2(20 CHAR), 
	"CONTENT" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"TIME" TIMESTAMP (6) DEFAULT systimestamp, 
	 CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."COMMENTS_TRG1" 
BEFORE INSERT ON COMMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."COMMENTS_TRG1" ENABLE;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."COMMENTS_TRG" 
BEFORE INSERT ON COMMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."COMMENTS_TRG" ENABLE;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."COMMENTS_TRG2" 
BEFORE INSERT ON COMMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."COMMENTS_TRG2" ENABLE;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."COMMENTS_TRG3" 
BEFORE INSERT ON COMMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COMMENT_ID IS NULL THEN
      SELECT COMMENTS_SEQ3.NEXTVAL INTO :NEW.COMMENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."COMMENTS_TRG3" ENABLE;

