CREATE TABLE "SCOTT"."COMMEND" 
   (	"BOARDID" NUMBER(8,0), 
	"RECOMMENDERID" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;