
  CREATE TABLE "SCOTT"."DEALREPLIES" 
   (	"ID" NUMBER(6,0) NOT NULL ENABLE, 
	"DEAL_ID" NUMBER(6,0), 
	"USER_NICKNAME" VARCHAR2(100 CHAR), 
	"USER_ID" VARCHAR2(100 CHAR), 
	"USER_RANKING" NUMBER(5,0), 
	"CONTENT" VARCHAR2(3000 CHAR) NOT NULL ENABLE, 
	"TIME" DATE DEFAULT systimestamp, 
	 CONSTRAINT "TRANSACTIONREPLY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "DEALREPLIES_POST_ID_FK" FOREIGN KEY ("DEAL_ID")
	  REFERENCES "SCOTT"."DEAL" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."TRANSACTIONREPLY_TRG" 
BEFORE INSERT ON "DEALREPLIES" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."TRANSACTIONREPLY_TRG" ENABLE;