
  CREATE TABLE "SCOTT"."DEAL" 
   (	"ID" NUMBER(8,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(3000 CHAR) NOT NULL ENABLE, 
	"NICKNAME" VARCHAR2(100 CHAR), 
	"USER_ID" VARCHAR2(100 CHAR), 
	"USER_RANKING" NUMBER(5,0), 
	"CREATED_TIME" DATE DEFAULT systimestamp, 
	"MODIFIED_TIME" DATE DEFAULT systimestamp, 
	 CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."TRANSACTION_TRG" 
BEFORE INSERT ON "DEAL" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TRANSACTION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."TRANSACTION_TRG" ENABLE;