--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-09-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUCTION
--------------------------------------------------------

  CREATE TABLE "SCOTT"."AUCTION" 
   (	"AID" NUMBER(8,0), 
	"PRODUCTID" NUMBER(8,0), 
	"AUCTIONEER" VARCHAR2(20 BYTE), 
	"BIDDER" VARCHAR2(20 BYTE), 
	"PASSBID" NUMBER(20,0) DEFAULT 0, 
	"NOWBID" NUMBER(20,0) DEFAULT 0, 
	"BIDCOUNT" NUMBER(20,0) DEFAULT 0, 
	"SUCCESSBID" NUMBER(20,0) DEFAULT 0, 
	"AUCTIONSTART" TIMESTAMP (6) DEFAULT systimestamp, 
	"AUCTIONEND" TIMESTAMP (6) DEFAULT systimestamp, 
	"AUCTIONNAME" VARCHAR2(50 CHAR), 
	"STATUS" NUMBER(4,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.AUCTION
SET DEFINE OFF;
Insert into SCOTT.AUCTION (AID,PRODUCTID,AUCTIONEER,BIDDER,PASSBID,NOWBID,BIDCOUNT,SUCCESSBID,AUCTIONSTART,AUCTIONEND,AUCTIONNAME,STATUS) values (21,21,'test','test',195000,58500,0,0,to_timestamp('23/06/08 17:35:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/06/10 17:36:00.000000000','RR/MM/DD HH24:MI:SSXFF'),'테스트',1);
Insert into SCOTT.AUCTION (AID,PRODUCTID,AUCTIONEER,BIDDER,PASSBID,NOWBID,BIDCOUNT,SUCCESSBID,AUCTIONSTART,AUCTIONEND,AUCTIONNAME,STATUS) values (6,22,'test','test',150000,156000,7,0,to_timestamp('23/06/07 18:15:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/06/09 18:15:00.000000000','RR/MM/DD HH24:MI:SSXFF'),'붓싼테스트',2);
Insert into SCOTT.AUCTION (AID,PRODUCTID,AUCTIONEER,BIDDER,PASSBID,NOWBID,BIDCOUNT,SUCCESSBID,AUCTIONSTART,AUCTIONEND,AUCTIONNAME,STATUS) values (22,21,'test','test',295000,112100,3,0,to_timestamp('23/06/08 09:55:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/06/09 09:58:00.000000000','RR/MM/DD HH24:MI:SSXFF'),'서울탁주류판',2);
Insert into SCOTT.AUCTION (AID,PRODUCTID,AUCTIONEER,BIDDER,PASSBID,NOWBID,BIDCOUNT,SUCCESSBID,AUCTIONSTART,AUCTIONEND,AUCTIONNAME,STATUS) values (8,1,'test','test',75000,76500,8,0,to_timestamp('23/06/08 12:06:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/06/22 12:06:00.000000000','RR/MM/DD HH24:MI:SSXFF'),'대한경매특판',2);
Insert into SCOTT.AUCTION (AID,PRODUCTID,AUCTIONEER,BIDDER,PASSBID,NOWBID,BIDCOUNT,SUCCESSBID,AUCTIONSTART,AUCTIONEND,AUCTIONNAME,STATUS) values (16,1,'test','test',120000,36000,0,0,to_timestamp('23/06/08 15:59:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/06/14 15:59:00.000000000','RR/MM/DD HH24:MI:SSXFF'),'경매만들기2',1);
Insert into SCOTT.AUCTION (AID,PRODUCTID,AUCTIONEER,BIDDER,PASSBID,NOWBID,BIDCOUNT,SUCCESSBID,AUCTIONSTART,AUCTIONEND,AUCTIONNAME,STATUS) values (14,1,'test','이붕이',100000,52000,17,0,to_timestamp('23/06/08 15:58:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/06/15 15:58:00.000000000','RR/MM/DD HH24:MI:SSXFF'),'테스트경매',1);
Insert into SCOTT.AUCTION (AID,PRODUCTID,AUCTIONEER,BIDDER,PASSBID,NOWBID,BIDCOUNT,SUCCESSBID,AUCTIONSTART,AUCTIONEND,AUCTIONNAME,STATUS) values (15,21,'test','test',100000,103000,18,0,to_timestamp('23/06/09 15:58:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/06/14 15:58:00.000000000','RR/MM/DD HH24:MI:SSXFF'),'채팅방 생성용',2);
--------------------------------------------------------
--  DDL for Index AU_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."AU_ID_PK" ON "SCOTT"."AUCTION" ("AID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger AUCTION_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."AUCTION_TRG" 
BEFORE INSERT ON AUCTION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "SCOTT"."AUCTION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUCTION_TRG1
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."AUCTION_TRG1" 
BEFORE INSERT ON AUCTION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."AUCTION_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUCTION_TRG2
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."AUCTION_TRG2" 
BEFORE INSERT ON AUCTION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.AID IS NULL THEN
      SELECT AUCTION_SEQ2.NEXTVAL INTO :NEW.AID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."AUCTION_TRG2" ENABLE;
--------------------------------------------------------
--  Constraints for Table AUCTION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."AUCTION" MODIFY ("AUCTIONEER" CONSTRAINT "AU_ACNEER_NN" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."AUCTION" MODIFY ("BIDDER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."AUCTION" ADD CONSTRAINT "AU_ID_PK" PRIMARY KEY ("AID")
  USING INDEX "SCOTT"."AU_ID_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUCTION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."AUCTION" ADD CONSTRAINT "AU_PID_FK" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "SCOTT"."AUCTIONPRODUCTS" ("PRODUCTID") ENABLE;
