--------------------------------------------------------
--  파일이 생성됨 - 수요일-6월-14-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BULLETINBOARD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BULLETINBOARD" 
   (	"BOARD_ID" NUMBER(8,0), 
	"TITLE" VARCHAR2(1000 CHAR), 
	"NICKNAME" VARCHAR2(100 CHAR), 
	"USER_ID" VARCHAR2(100 CHAR), 
	"TIME" DATE DEFAULT systimestamp, 
	"VIEWS" NUMBER(8,0) DEFAULT 0, 
	"RECOMMEND" NUMBER(8,0) DEFAULT 0, 
	"CONTENT" VARCHAR2(3000 CHAR), 
	"CATEGORY" NUMBER(1,0) DEFAULT 1, 
	"IMAGE" VARCHAR2(1000 CHAR) DEFAULT 'C:\workspace\lab-midproject\middlePj\alcohol\src\main\webapp\static\images\DefaultImage.png'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.BULLETINBOARD
SET DEFINE OFF;
Insert into SCOTT.BULLETINBOARD (BOARD_ID,TITLE,NICKNAME,USER_ID,TIME,VIEWS,RECOMMEND,CONTENT,CATEGORY,IMAGE) values (28,'2233','테슬라대주주','leechanhee@gmail.com',to_date('2023/06/14 18:27:01','YYYY/MM/DD HH24:MI:SS'),0,0,'222222',1,'C:\workspace\lab-midproject\middlePj\alcohol\src\main\webapp\static\images\c5cec32c-829d-455b-8916-ed54b78df410dc8b3d02-a15a-4afa-a88b-989cf2a50476.jpg');
Insert into SCOTT.BULLETINBOARD (BOARD_ID,TITLE,NICKNAME,USER_ID,TIME,VIEWS,RECOMMEND,CONTENT,CATEGORY,IMAGE) values (27,'1111122','테슬라대주주','leechanhee@gmail.com',to_date('2023/06/14 18:26:53','YYYY/MM/DD HH24:MI:SS'),0,0,'1122',1,'C:\workspace\lab-midproject\middlePj\alcohol\src\main\webapp\static\images\946c531a-4761-4d73-a231-8cc6626ec6469fc764ca0704ce3ebaba47c50f8b7e8f617ea012db208c18f6e83b1a90a7baa7.png');
Insert into SCOTT.BULLETINBOARD (BOARD_ID,TITLE,NICKNAME,USER_ID,TIME,VIEWS,RECOMMEND,CONTENT,CATEGORY,IMAGE) values (29,'312312','테슬라대주주','leechanhee@gmail.com',to_date('2023/06/14 18:28:00','YYYY/MM/DD HH24:MI:SS'),0,0,'312312',0,'C:\workspace\lab-midproject\middlePj\alcohol\src\main\webapp\static\images\57f8002d-580d-43cb-8a2b-8a605f0ea0a9mainBackground2.jpg');
--------------------------------------------------------
--  DDL for Index BULLETINBOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."BULLETINBOARD_PK" ON "SCOTT"."BULLETINBOARD" ("BOARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger BULLETINBOARD_TRG1
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."BULLETINBOARD_TRG1" 
BEFORE INSERT ON BULLETINBOARD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."BULLETINBOARD_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BULLETINBOARD_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."BULLETINBOARD_TRG" 
BEFORE INSERT ON BULLETINBOARD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."BULLETINBOARD_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BULLETINBOARD_TRG2
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."BULLETINBOARD_TRG2" 
BEFORE INSERT ON BULLETINBOARD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."BULLETINBOARD_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BULLETINBOARD_TRG3
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."BULLETINBOARD_TRG3" 
BEFORE INSERT ON BULLETINBOARD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."BULLETINBOARD_TRG3" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BULLETINBOARD_TRG4
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."BULLETINBOARD_TRG4" 
BEFORE INSERT ON BULLETINBOARD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.BOARD_ID IS NULL THEN
      SELECT BULLETINBOARD_SEQ4.NEXTVAL INTO :NEW.BOARD_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."BULLETINBOARD_TRG4" ENABLE;
--------------------------------------------------------
--  Constraints for Table BULLETINBOARD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BULLETINBOARD" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BULLETINBOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BULLETINBOARD" MODIFY ("BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BULLETINBOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BULLETINBOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BULLETINBOARD" ADD CONSTRAINT "BULLETINBOARD_PK" PRIMARY KEY ("BOARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
