--------------------------------------------------------
--  파일이 생성됨 - 화요일-6월-20-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."USERS" 
   (	"USERPASSWORD" VARCHAR2(20 CHAR), 
	"USERPASSWORDCHECK" VARCHAR2(20 CHAR), 
	"USERNAME" VARCHAR2(8 CHAR), 
	"USERADDRESS" VARCHAR2(50 CHAR), 
	"USERPHONE" VARCHAR2(20 CHAR), 
	"USEREMAIL" VARCHAR2(100 CHAR), 
	"USERAGE" NUMBER(3,0), 
	"USERGENDER" VARCHAR2(5 CHAR), 
	"USERBIRTHDAY" TIMESTAMP (6), 
	"USERJOINDATE" TIMESTAMP (6), 
	"USERRANKING" NUMBER(5,0), 
	"USERPOINT" NUMBER(8,0), 
	"USERNICKNAME" VARCHAR2(10 CHAR), 
	"CATEGORYS" NUMBER(1,0), 
	"DEACTIVATIONACCOUNT" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."USERS_PK" ON "SCOTT"."USERS" ("USEREMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."USERS_TRG1" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "SCOTT"."USERS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."USERS_TRG" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "SCOTT"."USERS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USEREMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERBIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERPASSWORDCHECK" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERPHONE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USEREMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERAGE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERGENDER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERJOINDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERNICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("CATEGORYS" NOT NULL ENABLE);
