--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-09-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PAYMENTCHECK
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PAYMENTCHECK" 
   (	"COUNT" NUMBER(4,0), 
	"PRODUCTINFO" VARCHAR2(300 BYTE), 
	"PRODUCTPRICE" VARCHAR2(100 BYTE), 
	"DELIVERYFEE" VARCHAR2(50 BYTE), 
	"TOTALPRICE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.PAYMENTCHECK
SET DEFINE OFF;
Insert into SCOTT.PAYMENTCHECK (COUNT,PRODUCTINFO,PRODUCTPRICE,DELIVERYFEE,TOTALPRICE) values (1,'koreanSoju','10,000','3,000','13,000');
--------------------------------------------------------
--  Constraints for Table PAYMENTCHECK
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PAYMENTCHECK" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PAYMENTCHECK" MODIFY ("PRODUCTINFO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PAYMENTCHECK" MODIFY ("PRODUCTPRICE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PAYMENTCHECK" MODIFY ("DELIVERYFEE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PAYMENTCHECK" MODIFY ("TOTALPRICE" NOT NULL ENABLE);
