--------------------------------------------------------
--  파일이 생성됨 - 수요일-6월-14-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PAYMENT_LIST
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PAYMENT_LIST" 
   (	"PAYMENTID" NUMBER, 
	"USERNICKNAME" VARCHAR2(8 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.PAYMENT_LIST
SET DEFINE OFF;
Insert into SCOTT.PAYMENT_LIST (PAYMENTID,USERNICKNAME) values (7,'다한');
Insert into SCOTT.PAYMENT_LIST (PAYMENTID,USERNICKNAME) values (1,'다한');
Insert into SCOTT.PAYMENT_LIST (PAYMENTID,USERNICKNAME) values (2,'다한');
Insert into SCOTT.PAYMENT_LIST (PAYMENTID,USERNICKNAME) values (3,'다한');
Insert into SCOTT.PAYMENT_LIST (PAYMENTID,USERNICKNAME) values (4,'다한');
Insert into SCOTT.PAYMENT_LIST (PAYMENTID,USERNICKNAME) values (5,'다한');
Insert into SCOTT.PAYMENT_LIST (PAYMENTID,USERNICKNAME) values (6,'다한');
Insert into SCOTT.PAYMENT_LIST (PAYMENTID,USERNICKNAME) values (8,'다한');
--------------------------------------------------------
--  DDL for Index PAYMENT_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PAYMENT_LIST_PK" ON "SCOTT"."PAYMENT_LIST" ("PAYMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger PAYMENT_LIST_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."PAYMENT_LIST_TRG" 
BEFORE INSERT ON PAYMENT_LIST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PAYMENTID IS NULL THEN
      SELECT PAYMENT_LIST_SEQ.NEXTVAL INTO :NEW.PAYMENTID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."PAYMENT_LIST_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT_LIST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PAYMENT_LIST" MODIFY ("PAYMENTID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PAYMENT_LIST" MODIFY ("USERNICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PAYMENT_LIST" ADD CONSTRAINT "PAYMENT_LIST_PK" PRIMARY KEY ("PAYMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
