--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-15-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PRODUCTS" 
   (	"PID" NUMBER(10,0), 
	"PRODUCTNAME" VARCHAR2(40 CHAR), 
	"STANDARD" VARCHAR2(20 CHAR), 
	"UNIT" VARCHAR2(20 CHAR), 
	"PRICE" NUMBER(10,0), 
	"BRAND" VARCHAR2(40 CHAR), 
	"USERID" VARCHAR2(40 CHAR), 
	"EXPIRATIONDATE" VARCHAR2(40 CHAR), 
	"ALCOHOL_LEVEL" NUMBER(10,2), 
	"HASHTAG" VARCHAR2(100 CHAR), 
	"PHOTOPATH" VARCHAR2(1000 CHAR), 
	"CATEGORY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.PRODUCTS
SET DEFINE OFF;
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (2,'대한맥주','500ml * 20','BOX',200000,'대한유통상회','다훈','냉장보관 시 30일',5.5,'가성비','C:\imgs\9347adfd-1122-4b41-b2ef-72dee4f2109e이름1.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (3,'맛있는전통술0','355ml','EA',0,'대한주류0','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',5);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (4,'맛있는전통술1','355ml','EA',100,'대한주류1','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',7);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (5,'맛있는전통술2','355ml','EA',200,'대한주류2','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (6,'맛있는전통술3','355ml','EA',300,'대한주류3','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (7,'맛있는전통술4','355ml','EA',400,'대한주류4','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (8,'맛있는전통술5','355ml','EA',500,'대한주류5','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (9,'맛있는전통술6','355ml','EA',600,'대한주류6','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',12);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (10,'맛있는전통술7','355ml','EA',700,'대한주류7','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (11,'맛있는전통술8','355ml','EA',800,'대한주류8','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (12,'맛있는전통술9','355ml','EA',900,'대한주류9','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (13,'맛있는전통술10','355ml','EA',1000,'대한주류10','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',1);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (14,'맛있는전통술11','355ml','EA',1100,'대한주류11','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (15,'맛있는전통술12','355ml','EA',1200,'대한주류12','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (16,'맛있는전통술13','355ml','EA',1300,'대한주류13','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (17,'맛있는전통술14','355ml','EA',1400,'대한주류14','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',10);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (18,'맛있는전통술15','355ml','EA',1500,'대한주류15','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (19,'맛있는전통술16','355ml','EA',1600,'대한주류16','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (20,'맛있는전통술17','355ml','EA',1700,'대한주류17','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',12);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (21,'맛있는전통술18','355ml','EA',1800,'대한주류18','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (22,'맛있는전통술19','355ml','EA',1900,'대한주류19','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (23,'맛있는전통술20','355ml','EA',2000,'대한주류20','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',12);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (24,'맛있는전통술21','355ml','EA',2100,'대한주류21','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',5);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (25,'맛있는전통술22','355ml','EA',2200,'대한주류22','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',5);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (26,'맛있는전통술23','355ml','EA',2300,'대한주류23','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',9);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (27,'맛있는전통술24','355ml','EA',2400,'대한주류24','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (28,'맛있는전통술25','355ml','EA',2500,'대한주류25','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (29,'맛있는전통술26','355ml','EA',2600,'대한주류26','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',3);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (30,'맛있는전통술27','355ml','EA',2700,'대한주류27','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (31,'맛있는전통술28','355ml','EA',2800,'대한주류28','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',10);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (32,'맛있는전통술29','355ml','EA',2900,'대한주류29','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (33,'맛있는전통술30','355ml','EA',3000,'대한주류30','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (34,'맛있는전통술31','355ml','EA',3100,'대한주류31','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (35,'맛있는전통술32','355ml','EA',3200,'대한주류32','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',5);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (36,'맛있는전통술33','355ml','EA',3300,'대한주류33','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',1);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (37,'맛있는전통술34','355ml','EA',3400,'대한주류34','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (38,'맛있는전통술35','355ml','EA',3500,'대한주류35','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (39,'맛있는전통술36','355ml','EA',3600,'대한주류36','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',9);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (40,'맛있는전통술37','355ml','EA',3700,'대한주류37','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (41,'맛있는전통술38','355ml','EA',3800,'대한주류38','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',1);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (42,'맛있는전통술39','355ml','EA',3900,'대한주류39','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (43,'맛있는전통술40','355ml','EA',4000,'대한주류40','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (44,'맛있는전통술41','355ml','EA',4100,'대한주류41','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (45,'맛있는전통술42','355ml','EA',4200,'대한주류42','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',10);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (46,'맛있는전통술43','355ml','EA',4300,'대한주류43','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (47,'맛있는전통술44','355ml','EA',4400,'대한주류44','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',7);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (48,'맛있는전통술45','355ml','EA',4500,'대한주류45','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (49,'맛있는전통술46','355ml','EA',4600,'대한주류46','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',12);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (50,'맛있는전통술47','355ml','EA',4700,'대한주류47','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (51,'맛있는전통술48','355ml','EA',4800,'대한주류48','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (52,'맛있는전통술49','355ml','EA',4900,'대한주류49','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',7);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (53,'맛있는전통술50','355ml','EA',5000,'대한주류50','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',6);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (54,'맛있는전통술51','355ml','EA',5100,'대한주류51','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (55,'맛있는전통술52','355ml','EA',5200,'대한주류52','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',12);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (56,'맛있는전통술53','355ml','EA',5300,'대한주류53','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',9);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (57,'맛있는전통술54','355ml','EA',5400,'대한주류54','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',3);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (58,'맛있는전통술55','355ml','EA',5500,'대한주류55','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',7);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (59,'맛있는전통술56','355ml','EA',5600,'대한주류56','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',3);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (60,'맛있는전통술57','355ml','EA',5700,'대한주류57','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (61,'맛있는전통술58','355ml','EA',5800,'대한주류58','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',5);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (62,'맛있는전통술59','355ml','EA',5900,'대한주류59','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (63,'맛있는전통술60','355ml','EA',6000,'대한주류60','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',10);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (64,'맛있는전통술61','355ml','EA',6100,'대한주류61','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',5);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (65,'맛있는전통술62','355ml','EA',6200,'대한주류62','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',3);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (66,'맛있는전통술63','355ml','EA',6300,'대한주류63','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (67,'맛있는전통술64','355ml','EA',6400,'대한주류64','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',9);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (68,'맛있는전통술65','355ml','EA',6500,'대한주류65','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (69,'맛있는전통술66','355ml','EA',6600,'대한주류66','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',7);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (70,'맛있는전통술67','355ml','EA',6700,'대한주류67','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',6);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (71,'맛있는전통술68','355ml','EA',6800,'대한주류68','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',3);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (72,'맛있는전통술69','355ml','EA',6900,'대한주류69','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (73,'맛있는전통술70','355ml','EA',7000,'대한주류70','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',1);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (74,'맛있는전통술71','355ml','EA',7100,'대한주류71','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (75,'맛있는전통술72','355ml','EA',7200,'대한주류72','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (76,'맛있는전통술73','355ml','EA',7300,'대한주류73','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (77,'맛있는전통술74','355ml','EA',7400,'대한주류74','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (78,'맛있는전통술75','355ml','EA',7500,'대한주류75','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',7);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (79,'맛있는전통술76','355ml','EA',7600,'대한주류76','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',12);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (80,'맛있는전통술77','355ml','EA',7700,'대한주류77','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',6);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (81,'맛있는전통술78','355ml','EA',7800,'대한주류78','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (82,'맛있는전통술79','355ml','EA',7900,'대한주류79','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (83,'맛있는전통술80','355ml','EA',8000,'대한주류80','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (84,'맛있는전통술81','355ml','EA',8100,'대한주류81','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',5);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (85,'맛있는전통술82','355ml','EA',8200,'대한주류82','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',12);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (86,'맛있는전통술83','355ml','EA',8300,'대한주류83','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',2);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (87,'맛있는전통술84','355ml','EA',8400,'대한주류84','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (88,'맛있는전통술85','355ml','EA',8500,'대한주류85','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',10);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (89,'맛있는전통술86','355ml','EA',8600,'대한주류86','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',1);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (90,'맛있는전통술87','355ml','EA',8700,'대한주류87','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',6);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (91,'맛있는전통술88','355ml','EA',8800,'대한주류88','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',5);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (92,'맛있는전통술89','355ml','EA',8900,'대한주류89','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',12);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (93,'맛있는전통술90','355ml','EA',9000,'대한주류90','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',12);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (94,'맛있는전통술91','355ml','EA',9100,'대한주류91','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',4);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (95,'맛있는전통술92','355ml','EA',9200,'대한주류92','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',10);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (96,'맛있는전통술93','355ml','EA',9300,'대한주류93','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (97,'맛있는전통술94','355ml','EA',9400,'대한주류94','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',3);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (98,'맛있는전통술95','355ml','EA',9500,'대한주류95','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',5);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (99,'맛있는전통술96','355ml','EA',9600,'대한주류96','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',10);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (100,'맛있는전통술97','355ml','EA',9700,'대한주류97','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',6);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (101,'맛있는전통술98','355ml','EA',9800,'대한주류98','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',8);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (102,'맛있는전통술99','355ml','EA',9900,'대한주류99','김돗개','2일 이내 섭취',15.5,'설명','C:\imgs\defaultimg.jpg',11);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (105,'다한탁주','155ml','EA',2500,'다한주류','다훈','2일이내',18.9,'탁주제일','C:\imgs\02b81e6b-b327-4688-91e6-a8cc808e1b70MBTI-2.PNG',1);
Insert into SCOTT.PRODUCTS (PID,PRODUCTNAME,STANDARD,UNIT,PRICE,BRAND,USERID,EXPIRATIONDATE,ALCOHOL_LEVEL,HASHTAG,PHOTOPATH,CATEGORY) values (106,'태욱청주','500ml * 15EA','BOX',40000,'태욱주류','다훈','구매 후 3일 이내',41.7,'대전의아들','C:\imgs\ee027ad6-d19d-411d-8b1a-b2d38575aaf5내 MBTI.PNG',1);
--------------------------------------------------------
--  DDL for Index SYS_C008478
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C008478" ON "SCOTT"."PRODUCTS" ("PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger PRODUCTS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."PRODUCTS_TRG1" 
BEFORE INSERT ON PRODUCTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PID IS NULL THEN
      SELECT PRODUCTS_SEQ1.NEXTVAL INTO :NEW.PID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."PRODUCTS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."PRODUCTS_TRG" 
BEFORE INSERT ON PRODUCTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."PRODUCTS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PRODUCTS" ADD PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."PRODUCTS" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PRODUCTS" MODIFY ("PRODUCTNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PRODUCTS" MODIFY ("STANDARD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PRODUCTS" MODIFY ("UNIT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PRODUCTS" MODIFY ("BRAND" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PRODUCTS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PRODUCTS" MODIFY ("EXPIRATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PRODUCTS" MODIFY ("ALCOHOL_LEVEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_FK1" FOREIGN KEY ("CATEGORY")
	  REFERENCES "SCOTT"."CATEGORY" ("CATEGORYID") ENABLE;
